BEGIN TRANSACTION;
DROP TABLE IF EXISTS "user";
CREATE TABLE IF NOT EXISTS "user" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"username"	TEXT UNIQUE,
	"password"	TEXT,
	"email"	TEXT UNIQUE,
	"userKey"	TEXT UNIQUE
);
DROP TABLE IF EXISTS "game";
CREATE TABLE IF NOT EXISTS "game" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"title"	TEXT NOT NULL DEFAULT 'Untitled',
	"starting_user_id" INTEGER,
	"opponent_user_id" INTEGER NOT NULL DEFAULT 120,
	"pieces" BLOB NOT NULL
);
COMMIT;
